presenters:
  lights: "redsun.presenter:LightPresenter"
  positioner: "redsun.presenter:PositionerPresenter"
views:
  logs: "redsun.view.qt.builtins:LogView"
  positioner: "redsun.view.qt.builtins:PositionerView"
