from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

from qtpy import QtWidgets as QtW
from qtpy.QtCore import QUrl
from qtpy.QtGui import QDesktopServices

from redsun.aio import run_coro
from redsun.log import Loggable
from redsun.storage import PATH_PROVIDER
from redsun.view import ViewPosition
from redsun.view.qt import QtView
from redsun.virtual import slot

if TYPE_CHECKING:
    from typing import Any

    from bluesky.protocols import Reading

    from redsun.storage import SessionPathProvider
    from redsun.virtual import VirtualContainer

_NO_ROOT_DIR = "No root directory provided."


class StorageView(QtView, Loggable):
    """View for configuring the output storage location.

    Displays and edits the root output directory of the session path provider
    shared under [`PATH_PROVIDER`][redsun.storage.PATH_PROVIDER]. Paths
    generated by that provider have the form::

        <base_dir>/<session>/<YYYY-MM-DD>/<plan>_<counter>

    The view never owns a provider: when nothing bound the key it degrades to a
    read-only placeholder.

    Parameters
    ----------
    name : str
        Identity key of the view. Passed as positional-only argument.
    kwargs : Any, optional
        Additional keyword arguments (unused).
    """

    @property
    def view_position(self) -> ViewPosition:
        """The position in the main view."""
        return ViewPosition.LEFT

    def __init__(self, name: str, /, **kwargs: Any) -> None:
        super().__init__(name, **kwargs)

        self._provider: SessionPathProvider | None = None

        self._root_dir_edit = QtW.QLineEdit()
        self._root_dir_edit.setReadOnly(True)
        self._root_dir_btn = QtW.QPushButton("Browse...")
        self._root_dir_btn.clicked.connect(self._on_browse_clicked)

        base_dir_row = QtW.QHBoxLayout()
        base_dir_row.addWidget(self._root_dir_edit)
        base_dir_row.addWidget(self._root_dir_btn)

        self._open_dir_btn = QtW.QPushButton("Open root directory")
        self._open_dir_btn.clicked.connect(self._on_open_dir_clicked)

        form = QtW.QFormLayout()
        form.addRow("Root directory", base_dir_row)

        root = QtW.QVBoxLayout(self)
        root.addLayout(form)
        root.addWidget(self._open_dir_btn)
        root.addStretch()
        self.setLayout(root)

    def inject_dependencies(self, container: VirtualContainer) -> None:
        """Resolve the session path provider and mirror its base directory."""
        provider = container.try_require(PATH_PROVIDER)
        if provider is None:
            self.logger.warning("No session path provider was shared.")
            self._root_dir_edit.setText(_NO_ROOT_DIR)
            self._root_dir_btn.setEnabled(False)
            return

        self._provider = provider
        self._root_dir_edit.setText(
            run_coro(provider.signals.base_dir.get_value()) or _NO_ROOT_DIR
        )
        container.subscribe(provider.signals.base_dir, self.update_base_dir)

    @slot
    def update_base_dir(self, reading: dict[str, Reading[str]]) -> None:
        """Show the base directory carried by a reading of the provider's signal."""
        value = next(iter(reading.values()))["value"]
        self._root_dir_edit.setText(value or _NO_ROOT_DIR)

    def _on_browse_clicked(self) -> None:
        if self._provider is None:
            return
        chosen = QtW.QFileDialog.getExistingDirectory(
            self,
            "Select output directory",
            self._root_dir_edit.text(),
        )
        if not chosen:
            return
        self._provider.set_base_dir(Path(chosen))

    def _on_open_dir_clicked(self) -> None:
        path = self._root_dir_edit.text()
        if path == _NO_ROOT_DIR:
            return
        QDesktopServices.openUrl(QUrl.fromLocalFile(path))


__all__ = ["StorageView"]
